/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from "@react-three/drei";
import { animate, useMotionValue } from "framer-motion";
import React, { useEffect } from "react";

export function Office(props) {
  const { section } = props;
  const { nodes, materials } = useGLTF("models/office-3d-2.glb");


  const textureOpacity = useMotionValue(0);
  const glassTextureOpacity = useMotionValue(0);

  useEffect(() => {
    animate(textureOpacity, section === 0 ? 1 : 0);
    animate(glassTextureOpacity, section === 0 ? 0.42 : 0);
  }, [section]);

  // materials["9"] = new THREE.MeshStandardMaterial({
  //   map: materials["9"].map,
  //   // color: "#534c60",
  // });

  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Wall.geometry}
        material={materials["3.001"]}
      />
      <group position={[-0.661, 1.499, -0.989]} scale={1.199}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane088.geometry}
          material={materials["9"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane088_1.geometry}
          material={materials["7.001"]}
        />
      </group>
      <group
        position={[-0.073, 1.112, -0.714]}
        rotation={[0, 0.385, 0]}
        scale={0.038}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder018.geometry}
          material={materials["9"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder018_1.geometry}
          material={materials["4.001"]}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Chair.geometry}
        material={materials["4.001"]}
        position={[-0.025, 0.157, -0.021]}
        rotation={[0.138, 0, 0.136]}
        scale={[0.53, 0.437, 0.53]}
      />
      <group position={[-1.077, 0.533, -0.794]} scale={1.103}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube020.geometry}
          material={materials["5.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube020_1.geometry}
          material={materials["2.001"]}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["Monitor_Stand_-_1"].geometry}
        material={materials["9"]}
        position={[-0.708, 1.119, -1.036]}
        scale={[0.155, 0.155, 0.092]}
      />
      <group
        position={[0.144, 1.533, -0.882]}
        rotation={[0, -0.355, -Math.PI / 2]}
        scale={[0.988, 1.199, 1.199]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane051.geometry}
          material={materials["9"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane051_1.geometry}
          material={materials["7.001"]}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["Monitor_Stand_-_2"].geometry}
        material={materials["9"]}
        position={[0.158, 1.072, -0.926]}
        rotation={[0, -0.355, 0]}
        scale={[0.155, 0.155, 0.092]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["Paper-Wall-Big"].geometry}
        material={materials["7.001"]}
        position={[-1.231, 1.333, 1.045]}
        rotation={[-0.325, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Framework.geometry}
        material={materials["4.001"]}
        position={[-1.239, 1.683, 0.633]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={[0.487, 0.487, 0.636]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["Pin-1"].geometry}
        material={materials["8.001"]}
        position={[-1.133, 1.502, 0.98]}
        rotation={[-0.325, 0, -Math.PI / 2]}
        scale={0.062}
      />
      <group
        position={[-1.19, 1.909, 0.294]}
        rotation={[1.681, 0, -Math.PI / 2]}
        scale={0.09}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane066.geometry}
          material={materials["8.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane066_1.geometry}
          material={materials["5.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane066_2.geometry}
          material={materials["9"]}
        />
      </group>
      <group position={[-1.202, 2.022, -0.612]} rotation={[0, 1.571, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane067.geometry}
          material={materials["9"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane067_1.geometry}
          material={materials["4.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane067_2.geometry}
          material={materials["6.001"]}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["Paper-Wall-Small"].geometry}
        material={materials["9"]}
        position={[-1.231, 1.33, 0.24]}
        rotation={[0.325, 0, -Math.PI]}
        scale={-0.745}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["Pin-2"].geometry}
        material={materials["5.001"]}
        position={[-1.133, 1.462, 0.299]}
        rotation={[0.325, 0, Math.PI / 2]}
        scale={-0.062}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.FloorBottom.geometry}
        material={materials["1.001"]}
        position={[-0.013, 1.259, -0.018]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Floor.geometry}
        material={materials["2.001"]}
        position={[0.245, 0.001, -0.046]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.974}
      />
      <group position={[-0.569, 1.101, -0.645]} scale={0.039}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane001.geometry}
          material={materials["9"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane001_1.geometry}
          material={materials["6.001"]}
        />
      </group>
      <group
        position={[1.124, 0.536, -0.691]}
        rotation={[-0.017, 0.006, -0.004]}
        scale={0.347}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh.geometry}
          material={materials["Brown orang long couch"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh_1.geometry}
          material={materials["black carbon"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["Book-Down"].geometry}
          material={materials["Material.016"]}
          position={[0.185, -2.105, 0.111]}
          rotation={[0, -0.598, 0]}
          scale={0.369}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["Book-Top"].geometry}
          material={materials["Green pandan long coach"]}
          position={[0.255, 0.165, 0.273]}
          rotation={[0, -0.003, 0]}
          scale={0.369}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube003.geometry}
            material={materials["Material.016"]}
          />
        </mesh>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube006.geometry}
          material={materials["dark green long coach"]}
          position={[0.185, -2.105, 0.111]}
          rotation={[0, -0.598, 0]}
          scale={0.369}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder.geometry}
          material={materials["orange krem long coach"]}
          position={[0.68, -1.075, 0.408]}
          rotation={[0, 0, 0.279]}
          scale={0.379}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Vert.geometry}
          material={materials["black carbon"]}
          position={[0.899, 0.132, -0.02]}
          rotation={[0, 0, -1.112]}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SayJeyHi.geometry}
        material={nodes.SayJeyHi.material}
        position={[-1.22, 1.256, 1.246]}
        rotation={[1.266, 0.007, -1.577]}
        scale={0.133}
      />
      <group
        position={[0.568, 1.116, -0.736]}
        rotation={[1.448, -0.094, 0.558]}
        scale={0.064}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh001.geometry}
          material={materials["dark brown loang coach"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh001_1.geometry}
          material={materials["Material.019"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh001_2.geometry}
          material={materials["Material.020"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle001.geometry}
          material={materials["orange krem long coach"]}
          position={[0.652, -0.076, -0.894]}
          rotation={[0, -0.262, 0]}
          scale={1.175}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder003.geometry}
          material={nodes.Cylinder003.material}
          position={[0.514, -0.14, 0.87]}
          rotation={[-1.309, 0, 0.127]}
          scale={4.447}
        />
      </group>
    </group>
  );
}

useGLTF.preload("models/office-3d-2.glb");
