/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
import { editable as e } from '@theatre/r3f'

export function Amsterdam(props) {
  const { nodes, materials } = useGLTF('/models/base-ams-10.glb')
  return (
    <e.group theatreKey="Amsterdam" {...props} dispose={null}>
      <group position={[0, 0, -0.024]} rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[-8.623, 1.298, 9.253]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Parts_geo_01_New_color_palette_mat_0004.geometry}
              material={materials['New_color_palette_mat.002']}
              scale={[1, 0.862, 1]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Parts_geo_07_New_color_palette_mat_0005.geometry}
              material={materials['New_color_palette_mat.002']}
              scale={[1, 0.862, 1]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Parts_geo_10_New_color_palette_mat_0008.geometry}
              material={materials['New_color_palette_mat.002']}
              scale={[1, 0.862, 1]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Parts_geo_14_New_color_palette_mat_0004.geometry}
              material={materials['New_color_palette_mat.002']}
              scale={[1, 0.862, 1]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Parts_geo_16_New_color_palette_mat_0005.geometry}
              material={materials['New_color_palette_mat.002']}
              scale={[1, 0.862, 1]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Parts_geo_19_New_color_palette_mat_0004.geometry}
              material={materials['New_color_palette_mat.002']}
              scale={[1, 0.862, 1]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Parts_geo_23_New_color_palette_mat_0004.geometry}
              material={materials['New_color_palette_mat.002']}
              scale={[1, 0.862, 1]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Parts_geo_25_New_color_palette_mat_0004.geometry}
              material={materials['New_color_palette_mat.002']}
              scale={[1, 0.862, 1]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Parts_geo_10_New_color_palette_mat_0007.geometry}
              material={materials['New_color_palette_mat.002']}
              scale={[1, 0.862, 1]}
            />
          </group>
        </group>
      </group>
      <group position={[0, 0, 0.02]} rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[-8.623, 1.298, 9.253]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Parts_geo_01_New_color_palette_mat_0005.geometry}
              material={materials['New_color_palette_mat.003']}
              position={[3.802, 0, 0]}
              scale={[1, 0.862, 1]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Parts_geo_10_New_color_palette_mat_0010.geometry}
              material={materials['New_color_palette_mat.003']}
              position={[3.802, 0, 0]}
              scale={[1, 0.862, 1]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Parts_geo_14_New_color_palette_mat_0005.geometry}
              material={materials['New_color_palette_mat.003']}
              position={[3.802, 0, 0]}
              scale={[1, 0.862, 1]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Parts_geo_10_New_color_palette_mat_0009.geometry}
              material={materials['New_color_palette_mat.003']}
              position={[3.802, 0, 0]}
              scale={[1, 0.862, 1]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Parts_geo_07_New_color_palette_mat_0006.geometry}
              material={materials['New_color_palette_mat.003']}
              scale={[1, 0.862, 1]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Parts_geo_19_New_color_palette_mat_0005.geometry}
              material={materials['New_color_palette_mat.003']}
              position={[3.802, 0, 0]}
              scale={[1, 0.862, 1]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Parts_geo_23_New_color_palette_mat_0005.geometry}
              material={materials['New_color_palette_mat.003']}
              position={[3.802, 0, 0]}
              scale={[1, 0.862, 1]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Parts_geo_25_New_color_palette_mat_0005.geometry}
              material={materials['New_color_palette_mat.003']}
              position={[3.802, 0, 0]}
              scale={[1, 0.862, 1]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Parts_geo_28_New_color_palette_mat_0003.geometry}
              material={materials['New_color_palette_mat.003']}
              position={[3.802, 0, 0]}
              scale={[1, 0.862, 1]}
            />
          </group>
        </group>
      </group>
      <group position={[-1.942, 0, 0]} rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[-8.623, 1.298, 9.253]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Parts_geo_11_New_color_palette_mat_0002.geometry}
              material={materials['New_color_palette_mat.009']}
              position={[3.802, 0, 0]}
              scale={[1, 0.862, 1]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Parts_geo_29_New_color_palette_mat_0002.geometry}
              material={materials['New_color_palette_mat.009']}
              position={[3.802, 0, 0]}
              scale={[1, 0.862, 1]}
            />
          </group>
        </group>
      </group>
      <group position={[-1.942, 0, 0.02]} rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[-8.623, 1.298, 9.253]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Parts_geo_10_New_color_palette_mat_0001.geometry}
              material={materials['New_color_palette_mat.010']}
              position={[3.802, 0, 0]}
              scale={[1, 0.862, 1]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Parts_geo_28_New_color_palette_mat_0001.geometry}
              material={materials['New_color_palette_mat.010']}
              position={[3.802, 0, 0]}
              scale={[1, 0.862, 1]}
            />
          </group>
        </group>
      </group>
      <group position={[-3.784, 0, 0]} rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[-8.623, 1.298, 9.253]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Parts_geo_11_New_color_palette_mat_0003.geometry}
              material={materials['New_color_palette_mat.011']}
              position={[3.802, 0, 0]}
              scale={[1, 0.862, 1]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Parts_geo_29_New_color_palette_mat_0003.geometry}
              material={materials['New_color_palette_mat.011']}
              position={[3.802, 0, 0]}
              scale={[1, 0.862, 1]}
            />
          </group>
        </group>
      </group>
      <group position={[-3.784, 0, 0.02]} rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[-8.623, 1.298, 9.253]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Parts_geo_10_New_color_palette_mat_0002.geometry}
              material={materials['New_color_palette_mat.012']}
              position={[3.802, 0, 0]}
              scale={[1, 0.862, 1]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Parts_geo_28_New_color_palette_mat_0002.geometry}
              material={materials['New_color_palette_mat.012']}
              position={[3.802, 0, 0]}
              scale={[1, 0.862, 1]}
            />
          </group>
        </group>
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Ground.geometry}
        material={materials['New_color_palette_mat.004']}
        position={[-8.576, 1.227, 9.205]}
      />
      <group position={[-8.623, 1.298, 9.253]}>
        <group position={[-6.202, 0.01, -2.657]} scale={[0.924, 0.924, 0.722]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.polySurface1_New_color_palette_mat_0001.geometry}
            material={materials.New_color_palette_mat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.polySurface11_New_color_palette_mat_0001.geometry}
            material={materials.New_color_palette_mat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.polySurface2_New_color_palette_mat_0001.geometry}
            material={materials.New_color_palette_mat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.polySurface20_New_color_palette_mat_0001.geometry}
            material={materials.New_color_palette_mat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.polySurface3_New_color_palette_mat_0001.geometry}
            material={materials.New_color_palette_mat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.polySurface4_New_color_palette_mat_0001.geometry}
            material={materials.New_color_palette_mat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.polySurface5_New_color_palette_mat_0001.geometry}
            material={materials.New_color_palette_mat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.polySurface6_New_color_palette_mat_0001.geometry}
            material={materials.New_color_palette_mat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.polySurface7_New_color_palette_mat_0001.geometry}
            material={materials.New_color_palette_mat}
          />
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Street_light_geo_017_New_color_palette_mat_0.geometry}
          material={materials.New_color_palette_mat}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Street_light_geo_022_New_color_palette_mat_0.geometry}
          material={materials.New_color_palette_mat}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Water_geo_Water_0.geometry}
          material={materials.Water}
          position={[0, 0, 0.047]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Parts_geo_02_New_color_palette_mat_0.geometry}
          material={materials.New_color_palette_mat}
          position={[3.802, 0, 0]}
          scale={[1, 0.862, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Parts_geo_11_New_color_palette_mat_0.geometry}
          material={materials.New_color_palette_mat}
          position={[3.802, 0, 0]}
          scale={[1, 0.862, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Parts_geo_13_New_color_palette_mat_0.geometry}
          material={materials.New_color_palette_mat}
          position={[3.802, 0, 0]}
          scale={[1, 0.862, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Parts_geo_16_New_color_palette_mat_0.geometry}
          material={materials.New_color_palette_mat}
          position={[3.802, 0, 0]}
          scale={[1, 0.862, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Parts_geo_17_New_color_palette_mat_0.geometry}
          material={materials.New_color_palette_mat}
          position={[3.802, 0, 0]}
          scale={[1, 0.862, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Parts_geo_11_New_color_palette_mat_0001.geometry}
          material={materials.New_color_palette_mat}
          position={[3.802, 0, 0]}
          scale={[1, 0.862, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Parts_geo_07_New_color_palette_mat_0001.geometry}
          material={materials.New_color_palette_mat}
          position={[3.802, 0, 0]}
          scale={[1, 0.862, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Parts_geo_08_New_color_palette_mat_0001.geometry}
          material={materials.New_color_palette_mat}
          position={[3.802, 0, 0]}
          scale={[1, 0.862, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Parts_geo_20_New_color_palette_mat_0001.geometry}
          material={materials.New_color_palette_mat}
          position={[3.802, 0, 0]}
          scale={[1, 0.862, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Parts_geo_22_New_color_palette_mat_0001.geometry}
          material={materials.New_color_palette_mat}
          position={[3.802, 0, 0]}
          scale={[1, 0.862, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Parts_geo_26_New_color_palette_mat_0001.geometry}
          material={materials.New_color_palette_mat}
          position={[3.802, 0, 0]}
          scale={[1, 0.862, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Parts_geo_29_New_color_palette_mat_0001.geometry}
          material={materials.New_color_palette_mat}
          position={[3.802, 0, 0]}
          scale={[1, 0.862, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Parts_geo_02_New_color_palette_mat_0003.geometry}
          material={materials.New_color_palette_mat}
          scale={[1, 0.862, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Parts_geo_08_New_color_palette_mat_0003.geometry}
          material={materials.New_color_palette_mat}
          scale={[1, 0.862, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Parts_geo_11_New_color_palette_mat_0005.geometry}
          material={materials.New_color_palette_mat}
          scale={[1, 0.862, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Parts_geo_13_New_color_palette_mat_0003.geometry}
          material={materials.New_color_palette_mat}
          scale={[1, 0.862, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Parts_geo_17_New_color_palette_mat_0003.geometry}
          material={materials.New_color_palette_mat}
          scale={[1, 0.862, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Parts_geo_20_New_color_palette_mat_0003.geometry}
          material={materials.New_color_palette_mat}
          scale={[1, 0.862, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Parts_geo_22_New_color_palette_mat_0003.geometry}
          material={materials.New_color_palette_mat}
          scale={[1, 0.862, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Parts_geo_26_New_color_palette_mat_0003.geometry}
          material={materials.New_color_palette_mat}
          scale={[1, 0.862, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Parts_geo_11_New_color_palette_mat_0006.geometry}
          material={materials.New_color_palette_mat}
          scale={[1, 0.862, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.People_geo_015_Old_atlas_0.geometry}
          material={materials.Old_atlas}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.People_geo_016_Old_atlas_0.geometry}
          material={materials.Old_atlas}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.People_geo_03_Old_atlas_0.geometry}
          material={materials.Old_atlas}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.People_geo_07_Old_atlas_0.geometry}
          material={materials.Old_atlas}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.People_geo_08_Old_atlas_0.geometry}
          material={materials.Old_atlas}
          position={[-10.35, -0.786, 0.526]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.People_geo_09_Old_atlas_0.geometry}
          material={materials.Old_atlas}
          position={[0.067, 0.033, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.People_geo_20_Old_atlas_0.geometry}
          material={materials.Old_atlas}
        />
      </group>
    </e.group>
  )
}

useGLTF.preload('/models/base-ams-10.glb')
