/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from '@react-three/drei'
import { animate, useMotionValue } from 'framer-motion'
import React, { useEffect } from 'react'

export function Office(props) {
  const { section } = props
  const { nodes, materials } = useGLTF('models/my-office.glb')

  const textureOpacity = useMotionValue(0)

  useEffect(() => {
    animate(textureOpacity, section === 0 ? 1 : 0)
  }, [section])

  return (
    <group {...props} dispose={null}>
      <group position={[-0.609, 1.674, -0.949]} scale={1.199}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MonitorBig.geometry}
          material={materials['9']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MonitorBig_1.geometry}
          material={materials['7.001']}
        />
      </group>
      <group position={[0.102, 1.269, -0.655]} rotation={[0, -0.288, 0]} scale={0.03}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder018.geometry}
          material={materials['9']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder018_1.geometry}
          material={materials['4.001']}
        />
      </group>
      <group position={[-1.077, 0.688, -0.794]} scale={1.103}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube020.geometry}
          material={materials['5.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube020_1.geometry}
          material={materials.Items}
        />
      </group>
      <group
        position={[0.198, 1.684, -0.882]}
        rotation={[0, -0.31, -Math.PI / 2]}
        scale={[0.988, 1.199, 1.199]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.ManitorSmall.geometry}
          material={materials['9']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.ManitorSmall_1.geometry}
          material={materials['7.001']}
        />
      </group>
      <group position={[-0.959, 2.674, -1.004]} rotation={[0, 0.001, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane067.geometry}
          material={materials['9']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane067_1.geometry}
          material={materials['4.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane067_2.geometry}
          material={materials['6.001']}
        />
      </group>
      <group position={[-0.508, 1.247, -0.645]} scale={0.039}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane001.geometry}
          material={materials['9']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane001_1.geometry}
          material={materials['6.001']}
        />
      </group>
      <group position={[1.087, 0.536, -0.658]} rotation={[-0.017, 0.006, -0.004]} scale={0.347}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh.geometry}
          material={materials['Brown orang long couch']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh_1.geometry}
          material={materials['black carbon']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['Book-Down'].geometry}
          material={materials['Material.016']}
          position={[0.007, -0.439, 0.188]}
          rotation={[0, -0.598, 0]}
          scale={0.369}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['Book-Top'].geometry}
          material={materials['Green pandan long coach']}
          position={[0.255, 0.165, 0.273]}
          rotation={[0, -0.003, 0]}
          scale={0.369}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube003.geometry}
            material={materials['Material.016']}
          />
        </mesh>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder.geometry}
          material={materials['orange krem long coach']}
          position={[0.68, -1.075, 0.408]}
          rotation={[0, 0, 0.279]}
          scale={0.379}
        />
      </group>
      <group position={[-1.006, 2.501, 0.882]} rotation={[0, Math.PI / 2, 0]} scale={0.267}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube011.geometry}
          material={materials['orange.001']}
          position={[6.696, 0.102, 7.508]}
          rotation={[0, -1.562, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube012.geometry}
            material={materials['white new']}
            position={[0, -0.519, 0.375]}
            rotation={[-0.503, 0, 0]}
            scale={[1.004, 0.688, 0.688]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube013.geometry}
            material={materials['white new']}
            position={[0, -0.622, 0.089]}
            rotation={[-0.277, 0, 0]}
            scale={[1.004, 0.688, 0.688]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube014.geometry}
            material={materials['white new']}
            position={[0, 0, -0.196]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube015.geometry}
            material={materials['white new']}
            position={[-0.054, 0, 0]}
          />
        </mesh>
      </group>
      <group
        position={[1.086, 1.813, -1.019]}
        rotation={[Math.PI / 2, 0, -0.016]}
        scale={[0.15, 0.15, 0.104]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane081.geometry}
          material={materials['hijau.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane081_1.geometry}
          material={materials['orange.002']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane081_2.geometry}
          material={materials.yellow}
        />
      </group>
      <group position={[-0.533, 0.856, 0.369]} rotation={[Math.PI, -1.518, Math.PI]} scale={0.229}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder003.geometry}
          material={materials['Material.003']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder003_1.geometry}
          material={materials['Material.004']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder003_2.geometry}
          material={materials['Material.008']}
        />
      </group>
      <group position={[0.993, 0.849, -0.66]} scale={0.031}>
        <group position={[2.294, 1.148, 0]} scale={8.47}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder072.geometry}
            material={materials['Material.008']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder072_1.geometry}
            material={materials['Material.001']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder072_2.geometry}
            material={materials['Material.009']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder072_3.geometry}
            material={materials['Material.005']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder072_4.geometry}
            material={materials['Material.002']}
          />
        </group>
      </group>
      <group position={[-1.573, 0.995, -0.589]} rotation={[0, -0.827, 0]} scale={0.029}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder019.geometry}
          material={materials['C-2']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder019_1.geometry}
          material={materials['C-3']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder019_2.geometry}
          material={materials['C-1']}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane.geometry}
        material={materials['Material.015']}
        position={[-0.203, 0.111, 0]}
        scale={[1.666, 1, 1.162]}
      />
      <group position={[0.543, 1.282, -0.583]} rotation={[1.169, -0.031, 0.073]} scale={0.03}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle001.geometry}
          material={materials['Material.013']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle001_1.geometry}
          material={materials['Material.010']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle001_2.geometry}
          material={materials['Material.011']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle001_3.geometry}
          material={materials['Material.012']}
        />
      </group>
    </group>
  )
}

useGLTF.preload('models/my-office.glb')
