/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from '@react-three/drei'
import { animate, useMotionValue } from 'framer-motion'
import React, { useEffect } from 'react'

export function Office(props) {
  const { section } = props
  const { nodes, materials } = useGLTF('models/office-3d-2.glb')

  const textureOpacity = useMotionValue(0)
  const glassTextureOpacity = useMotionValue(0)

  useEffect(() => {
    animate(textureOpacity, section === 0 ? 1 : 0)
    animate(glassTextureOpacity, section === 0 ? 0.42 : 0)
  }, [section])

  // materials["9"] = new THREE.MeshStandardMaterial({
  //   map: materials["9"].map,
  //   // color: "#534c60",
  // });

  return (
    <group {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.Wall.geometry} material={materials['3.001']} />
      <group position={[-0.661, 1.499, -0.989]} scale={1.199}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane088.geometry}
          material={materials['9']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane088_1.geometry}
          material={materials['7.001']}
        />
      </group>
      <group position={[0.102, 1.112, -0.655]} rotation={[0, -0.288, 0]} scale={0.03}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder018.geometry}
          material={materials['9']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder018_1.geometry}
          material={materials['4.001']}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Chair.geometry}
        material={materials['4.001']}
        position={[-0.2, 0.157, -0.021]}
        rotation={[0.141, -0.193, 0.163]}
        scale={[0.53, 0.437, 0.53]}
      />
      <group position={[-1.077, 0.533, -0.794]} scale={1.103}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube020.geometry}
          material={materials['5.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube020_1.geometry}
          material={materials['2.001']}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['Monitor_Stand_-_1'].geometry}
        material={materials['9']}
        position={[-0.708, 1.119, -1.036]}
        scale={[0.155, 0.155, 0.092]}
      />
      <group
        position={[0.144, 1.533, -0.882]}
        rotation={[0, -0.355, -Math.PI / 2]}
        scale={[0.988, 1.199, 1.199]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane051.geometry}
          material={materials['9']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane051_1.geometry}
          material={materials['7.001']}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['Monitor_Stand_-_2'].geometry}
        material={materials['9']}
        position={[0.158, 1.072, -0.926]}
        rotation={[0, -0.355, 0]}
        scale={[0.155, 0.155, 0.092]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['Paper-Wall-Big'].geometry}
        material={materials['7.001']}
        position={[-1.231, 1.333, 1.045]}
        rotation={[-0.325, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Framework.geometry}
        material={materials['4.001']}
        position={[-1.239, 1.683, 0.633]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={[0.487, 0.487, 0.636]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['Pin-1'].geometry}
        material={materials['8.001']}
        position={[-1.133, 1.502, 0.98]}
        rotation={[-0.325, 0, -Math.PI / 2]}
        scale={0.062}
      />
      <group position={[-1.19, 1.909, 0.294]} rotation={[1.681, 0, -Math.PI / 2]} scale={0.09}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane066.geometry}
          material={materials['8.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane066_1.geometry}
          material={materials['5.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane066_2.geometry}
          material={materials['9']}
        />
      </group>
      <group position={[-1.202, 2.022, -0.612]} rotation={[0, 1.571, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane067.geometry}
          material={materials['9']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane067_1.geometry}
          material={materials['4.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane067_2.geometry}
          material={materials['6.001']}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['Paper-Wall-Small'].geometry}
        material={materials['9']}
        position={[-1.231, 1.33, 0.24]}
        rotation={[0.325, 0, -Math.PI]}
        scale={-0.745}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['Pin-2'].geometry}
        material={materials['5.001']}
        position={[-1.133, 1.462, 0.299]}
        rotation={[0.325, 0, Math.PI / 2]}
        scale={-0.062}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.FloorBottom.geometry}
        material={materials['1.001']}
        position={[-0.013, 1.259, -0.018]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Floor.geometry}
        material={materials['2.001']}
        position={[0.245, 0.001, -0.046]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.974}
      />
      <group position={[-0.488, 1.101, -0.645]} scale={0.039}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane001.geometry}
          material={materials['9']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane001_1.geometry}
          material={materials['6.001']}
        />
      </group>
      <group position={[1.075, 0.536, -0.691]} rotation={[-0.017, 0.006, -0.004]} scale={0.347}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh.geometry}
          material={materials['Brown orang long couch']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh_1.geometry}
          material={materials['black carbon']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['Book-Down'].geometry}
          material={materials['Material.016']}
          position={[0.007, -0.439, 0.188]}
          rotation={[0, -0.598, 0]}
          scale={0.369}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['Book-Top'].geometry}
          material={materials['Green pandan long coach']}
          position={[0.255, 0.165, 0.273]}
          rotation={[0, -0.003, 0]}
          scale={0.369}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube003.geometry}
            material={materials['Material.016']}
          />
        </mesh>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder.geometry}
          material={materials['orange krem long coach']}
          position={[0.68, -1.075, 0.408]}
          rotation={[0, 0, 0.279]}
          scale={0.379}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SayJeyHi.geometry}
        material={nodes.SayJeyHi.material}
        position={[-1.22, 1.256, 1.246]}
        rotation={[1.266, 0.007, -1.577]}
        scale={0.133}
      />
      <group position={[1.032, 1.425, -1.383]} scale={0.312}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['04fcc21a-e9b6-15af-1f4a-bdc0ade6d162'].geometry}
          material={materials['texture.png']}
          rotation={[0, Math.PI / 4, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['1491a257-ae4a-e4bf-e206-736f646c9efe'].geometry}
          material={materials['texture.png']}
          position={[0.063, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['15771a36-724d-9550-5608-aa4001d277ec'].geometry}
          material={materials['texture.png']}
          position={[-0.219, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['18507f3c-a866-2651-f03f-9c1971451954'].geometry}
          material={materials['texture.png']}
          rotation={[0, -Math.PI / 4, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['1e7c5ae1-4a7b-8770-f052-579e45efb554'].geometry}
          material={materials['texture.png']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['2121e2aa-c8e6-111b-30ba-913cc2ba8053'].geometry}
          material={materials['texture.png']}
          rotation={[0, -Math.PI / 4, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['24bc3736-3457-f9e2-5311-75f93f87f78a'].geometry}
          material={materials['texture.png']}
          rotation={[0, -Math.PI / 4, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['3035d188-176c-db3c-a043-a0f3696053e6'].geometry}
          material={materials['texture.png']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['33b0bfde-ad8f-781c-36d5-bf62acbd3d14'].geometry}
          material={materials['texture.png']}
          rotation={[0, -Math.PI / 4, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['3c882947-9bf7-7378-786e-bae260e93e33'].geometry}
          material={materials['texture.png']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['3d525bd8-d5c3-748c-4fa8-626ac72017be'].geometry}
          material={materials['texture.png']}
          rotation={[0, Math.PI / 4, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['3d921d9a-6c87-c734-7e06-fd921be33590'].geometry}
          material={materials['texture.png']}
          rotation={[0, -Math.PI / 4, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['43fceade-6433-1b6b-bfdc-0b6b4d3dac6d'].geometry}
          material={materials['texture.png']}
          rotation={[0, Math.PI / 4, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['45afd6d5-507d-de2f-6527-f3181d1e3f94'].geometry}
          material={materials['texture.png']}
          position={[0.063, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['47c9ea84-591d-9f99-45a9-93997613d996'].geometry}
          material={materials['texture.png']}
          rotation={[0, Math.PI / 4, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['4dbe6132-3216-7ca5-0506-6ec5bdbc9d22'].geometry}
          material={materials['texture.png']}
          rotation={[0, -Math.PI / 4, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['5225af6c-b95d-2324-32b8-1e02b4cdcd5e'].geometry}
          material={materials['texture.png']}
          rotation={[0, -Math.PI / 4, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['563ea3db-f3d4-34b7-4653-90862063c2b0'].geometry}
          material={materials['texture.png']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['570cb913-f053-a6bd-e6e6-0de7e8ad3f44'].geometry}
          material={materials['texture.png']}
          rotation={[0, -Math.PI / 4, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['58a58fa0-6499-0729-1161-52b3d57748c5'].geometry}
          material={materials['texture.png']}
          rotation={[0, Math.PI / 4, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['5ae4b962-342c-b00e-84b8-0ca30ce7c25e'].geometry}
          material={materials['texture.png']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['5e6e21b4-53af-73ec-8234-4e9ead702397'].geometry}
          material={materials['texture.png']}
          rotation={[0, Math.PI / 4, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['61f04aa0-c7d0-43b0-707c-13ea89d4b8c6'].geometry}
          material={materials['texture.png']}
          rotation={[0, -Math.PI / 4, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['64b6d90c-3ec0-0956-d954-0aff89e1196c'].geometry}
          material={materials['texture.png']}
          position={[0.031, 0, -0.156]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['6983e8c2-f553-3e83-0c97-9605cd85b7ae'].geometry}
          material={materials['texture.png']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['70f2970d-3396-9b2a-25da-2639539faf1a'].geometry}
          material={materials['texture.png']}
          rotation={[0, Math.PI / 4, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['78fb1f1b-5a7d-32ef-0d00-cd0fe5336552'].geometry}
          material={materials['texture.png']}
          rotation={[0, Math.PI / 4, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['8ad1aba7-6058-9d1d-52b6-902ffd08b9ed'].geometry}
          material={materials['texture.png']}
          rotation={[0, -Math.PI / 4, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['8b7f0307-f197-3a86-0fbd-080373455fdb'].geometry}
          material={materials['texture.png']}
          rotation={[0, Math.PI / 4, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['8bb4a5da-8d3c-21e7-db2a-261de53801cd'].geometry}
          material={materials['texture.png']}
          rotation={[0, Math.PI / 4, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['93c89d4f-bd32-e331-24e5-5696f056d638'].geometry}
          material={materials['texture.png']}
          rotation={[0, Math.PI / 4, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['9f30d049-fa5b-b105-c86a-a7e02943dbd4'].geometry}
          material={materials['texture.png']}
          rotation={[0, Math.PI / 4, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['a1da282f-81a3-a8a4-9767-2d00f466cf43'].geometry}
          material={materials['texture.png']}
          rotation={[0, -Math.PI / 4, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['ad8fa827-8306-c584-5784-5419cc3b7437'].geometry}
          material={materials['texture.png']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['bf7b8ffe-4a86-0dd4-df45-875f8a423d97'].geometry}
          material={materials['texture.png']}
          rotation={[0, Math.PI / 4, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['c272a0a4-c060-a084-53c6-deca8b51fb7f'].geometry}
          material={materials['texture.png']}
          rotation={[0, Math.PI / 4, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['c2dc8b28-f057-f03c-4490-4a2159c63290'].geometry}
          material={materials['texture.png']}
          rotation={[0, Math.PI / 4, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['c460a9ef-2fa1-1e0d-fc03-31bafd593c78'].geometry}
          material={materials['texture.png']}
          rotation={[0, Math.PI / 4, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['c5c1eb7b-3b58-be46-eec1-133c23d4a1c4'].geometry}
          material={materials['texture.png']}
          position={[0.031, 0, -0.156]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['c8742578-a6fa-5514-76f3-0d1157c229da'].geometry}
          material={materials['texture.png']}
          rotation={[0, -Math.PI / 4, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['c9406647-832c-214b-089a-d8ee90c78cd2'].geometry}
          material={materials['texture.png']}
          rotation={[0, Math.PI / 4, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['c9e40064-2f60-6790-8647-941a67992a50'].geometry}
          material={materials['texture.png']}
          rotation={[0, -Math.PI / 4, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['ca344d65-e06c-7fa6-c20a-ef2c46758fc7'].geometry}
          material={materials['texture.png']}
          rotation={[0, -Math.PI / 4, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['f4e87b8e-f0b4-4df7-24c2-1de7e738499d'].geometry}
          material={materials['texture.png']}
          position={[-0.219, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['fa3a5841-dfb7-cfb1-8588-fbc2e1a4218d'].geometry}
          material={materials['texture.png']}
          rotation={[0, -Math.PI / 4, 0]}
        />
      </group>
    </group>
  )
}

useGLTF.preload('models/office-3d-2.glb')
